version: 2
dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
  pre:
    - yarn global add lerna
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn --version
      - run: yarn install
      - run: lerna bootstrap
      - run: yarn test
      - store_artifacts:
          path: ./errorShots/
          when: always
