version: 2
machine:
  environment:
    CI: "true"
  node:
    version: 9.6.1
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn --version
      - run: yarn
      - run: yarn lerna:install
      - run: yarn lerna:test
      - store_artifacts:
          path: ./errorShots/
          when: always
