version: 2
machine:
  environment:
    CI: "true"
  node:
    version: 9.6.1
dependencies:
  override:
    - yarn
test:
  override:
    - yarn test
aliases:
  - &restore-node-modules-cache
    keys:
      - v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache
    keys:
      - v1-yarn-cache

  - &save-node-modules-cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    paths:
      - ~/.yarn-cache
    key: v1-yarn-cache
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-node-modules-cache
      - run: yarn --version
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn run deploy
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - store_artifacts:
          path: ./coverage
          when: always