version: 2
machine:
  environment:
    CI: "true"
  node:
    version: 9.6.1
aliases:
  - &restore-node-modules-cache
    keys:
      - v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache
    keys:
      - v1-yarn-cache

  - &save-node-modules-cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    paths:
      - ~/.yarn-cache
    key: v1-yarn-cache
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-node-modules-cache
      - run: yarn --version
      - run: yarn
      - run: yarn lerna:install
      - run: yarn lerna:test
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - store_artifacts:
          path: ./packages/summer-2018/coverage
          when: always
deployment:
  prod:
    branch: master
    commands:
      - checkout